### ISSUE TITLE
增加训练的脚本

### ISSUE THREAD

**Issue by Jensendd** [JUNZHU-SEIS/USTC-Pickers#2]
您好，可以上传你做训练的脚本吗？

**Comment by JUNZHU-SEIS** [comment]
抱歉，我没有系统整理过训练代码，也没有写相应的训练教程所以不便公开。如果您确实需要，我可以将相关脚本私发到您邮箱。包括：dataloader.py，train.py，augmentation.py，里面涵盖了训练模型的一些细节操作。因为我没有权限公开训练的数据集，所以这些代码仍需要您手动更改去适配您本地的训练数据。

**Comment by Jensendd** [comment]
@JUNZHU-SEIS 感谢回复！您方便的话将脚本直接发我邮箱吧，十分感谢！

**Comment by JUNZHU-SEIS** [comment]
[train_ustc_picker_util.zip](https://github.com/JUNZHU-SEIS/USTC-Pickers/files/13317547/train_ustc_picker_util.zip)
